### ISSUE TITLE
Current version no longer works / relies on the deprecated actions/github wrapper

### ISSUE THREAD

**Issue by banagale** [alexleventer/github-issue-due-dates-action#44]
This project is a great idea, but from what I can tell the current version does not work using the readme instructions.

In looking at fixing it I found it relies on [actions/github](https://github.com/actions/github) has been deprecated in favor of [actions/github-script](https://github.com/actions/github-script.),

Found this while trying to run test, which fails in Octokit.ts at `removeLabelsFromIssue`.

If I can, I'll try to update the project. Would be useful to me.

**Comment by alexleventer** [comment]
Thanks - thing should be running properly again.

Are you sure? 

https://www.npmjs.com/package/@actions/github
https://github.com/actions/toolkit/tree/master/packages/github
